version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/ubuntu-bionic/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/ubuntu-old-after-latest/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/ubuntu-latest/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/ubuntu-focal-with-date/"
    schedule:
      interval: "daily"
